LibMetrics.Test/Integration/PackagistRepositoryTest.cs
LibMetrics/FileSystemInfoExtensions.cs
LibMetrics/Languages/Php/ComposerRepository.cs

`symfony/css-selector` version `v3.4.37` was released on 2020/01/01. But version `v5.0.2` was released on 2019/11/18. The `LatestAsOf` method is incorrectly assuming that the most recently published package is the latest one. It instead should be returning the highest version number that was published as of the specified date. That would be `v5.0.2` in this case.
This pull request has been seeded with a failing test case. A good first issue for anyone looking to contribute. :)

Bug: incorrect php version for symfony/css-selector as of 2020/01/01

---

.gitignore
Freshli/Exceptions/DependencyNotFoundException.cs
Freshli/Exceptions/LatestVersionNotFoundException.cs
Freshli/Languages/Ruby/RubyGemsRepository.cs
Freshli/LibYearCalculator.cs
Freshli/Program.cs
Freshli/Runner.cs

Makes updates to initially resolve the following issues:
- #27 (https://github.com/chriskiehl/Gooey)
- #32 (https://github.com/HelloZeroNet/ZeroNet)
- #33 (https://github.com/diaspora/diaspora)
- #35 (https://github.com/gitlabhq/gitlabhq)
- #36 (https://github.com/discourse/discourse)
Note - these updates simply allow Freshli to successfully complete a run against the given repositories. The current logic simply skips problematic dependencies. These problematic dependencies still need to be investigated separately.

Add workaround when dependency errs or is not found

---

Freshli/Languages/Python/Conversions.cs

Fixes the outstanding eclint error by adding a line break to a line that was too long.

Fix eclint error

---

.gitignore
Freshli.Test/Acceptance.RubyGemsClearanceHistoryViaGitHub.approved.txt
Freshli.Test/Acceptance.RubyGemsFeedbinHistoryViaGitHub.approved.txt
Freshli.Test/Integration/Languages/Perl/MetaCpanRepositoryTest.cs
Freshli.Test/Integration/Languages/Php/PackagistRepositoryTest.cs
Freshli.Test/Integration/Languages/Python/PyPIRepositoryTest.cs
Freshli.Test/Integration/Languages/Ruby/RubyGemsRepositoryTest.cs
Freshli.Test/Integration/LibYearCalculatorTest.cs
Freshli.Test/Unit/SemVerVersionInfoTest.cs
Freshli/Exceptions/VersionNotFoundException.cs
Freshli/IPackageRepository.cs
Freshli/IVersionInfo.cs
Freshli/Languages/Perl/MetaCpanRepository.cs
Freshli/Languages/Php/ComposerRepository.cs
Freshli/Languages/Php/MulticastComposerRepository.cs
Freshli/Languages/Python/PyPIRepository.cs
Freshli/Languages/Ruby/RubyGemsRepository.cs
Freshli/Languages/Ruby/RubyGemsVersionInfo.cs
Freshli/LibYearCalculator.cs
Freshli/Runner.cs
Freshli/SemVerVersionInfo.cs

Per #153, updates logic to include Ruby pre-release dependency versions if the manifest version is a pre-release version.
This PR only updates the logic for Ruby. Other supported languages will need to be updated if/when issues arise. 
Additionally, a configurable option to output the results to a local file was added.

#153 - Add support for Ruby pre-release versions

---

Freshli/Languages/Python/Conversions.cs

This change annotates the PythonVersionInfo class to enable nullable references. This clears the warning and indicates intent to work with nullable references. 
C# 8.0 added the nullable annotation to allow for fine-grain control on the nullability of references. This annotation also allows for the change to the SafeToLower and SafeExtract methods, that can potentially return null, to return Nullable strings which further enables null-safe checking.
More information is available [Microsoft's Nullable documentation.](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references#nullable-annotation-context)
Enabling this annotation and adding the nullable `?` to the `string` return types of SafeToLower and SafeExtract eliminated that warnings in the build and should help future …

Enables Nullability for PythonVersionInfo

---

.github/workflows/dotnet-core.yml
Freshli.Test/Acceptance.cs
Freshli.Test/Freshli.Test.csproj
Freshli/Freshli.csproj
global.json

This should address the goals of  #193 (Change build target to .NET 5.0).
This also sets the `rollForward` setting in `global.json` to `latestMinor`. That way, it should make it easier for people who are trying to build the project using slightly newer, but still very likely compatible, versions of the .NET SDK.

Migrates to .NET 5.0

---

README.md

While reading through the documentation, I had to go through and update my copy of .NET Core SDK. Thinking it'll be useful to have the link to download the latest version of the SDK available right in the documentation.

Adds .NET Core SDK download link to documentation

---

Freshli/Freshli.csproj

This fixes the dependency necessary to enable development in a Ubuntu 20.04LTS environment as detailed in issue #206.
The updates enclosed include an update to the .NET core SDK minor version and an update to the package version of LibGit2Sharp.
As of these updates, Freshli successfully builds, runs, and passes the testing suite on Ubuntu 20.04; however, I am concerned about how this might affect the other operating systems and would be grateful if someone could ensure that these changes don't negatively affect development on Mac or Windows. If there are any other necessary changes needed, then I will definitely be willing to work for a different resolution! 😄
Associated Commit: https://github.com/corgibytes/freshli/commit/df6a532ca4207b893187fa52cece76975aef4b6b

Fixed dependency for Ubuntu 20LTS environment

---

.github/workflows/dotnet-core.yml

This activates `release` branches for builds, which will allow for beta packages to be deployed to Github Packages.

Allows release branches to run build

---

.github/workflows/release-notes.yml
CHANGELOG.md
GitReleaseManager.yaml

Fixes #266.  Also updated the release notes CI to use `freshli-lib` repo instead of `freshli`.
Note: While testing this fix I regenerated the [v0.3.0](https://github.com/corgibytes/freshli-lib/releases/tag/v0.3.0) text and created the [v0.4.0](https://github.com/corgibytes/freshli-lib/releases/tag/untagged-4fd8dfc9838018f9d6ae) draft release.

Fixed issue with labels in release note CI

---

.github/workflows/release-notes.yml
CHANGELOG.md

GitHub Actions are running on the commit that updates the changelog is added. This is causing some strange issues which appear to put a pull request in a strange state if there are no commits that come after the commit that modifies the changelog. Disabling the CI running on these changes _should_ do the trick.
Here's the strange state that the pull request is getting into:
Here's the checks that were run on the changelog commit:
And here are the checks that ran on the commit that triggered the creation of the changelog:
Those screenshots were taken shortly after the creation of #286. This was also observed on #243, but the pull request is no longer in that state because another commit has been added.

Solve `Some checks haven't completed yet` issue caused by use of `git-auto-commit-action`

---

CHANGELOG.md
README.md

The secret used by GitHub Actions to send code coverage has also been updated to point to the new location.

Moves CodeClimate links to a publicly accessible open-source account

---

.github/workflows/release-notes.yml

Fixes #293.  Might also have to make remove the release note generation from the branch protection but not sure yet.

Only generate release notes on push and not PR

---

.github/workflows/dotnet-core.yml
Corgibytes.Freshli.sln

Depdendabot does not allow GitHub secrets to be used so submitting the test results will Code Climate will fail on protected branches.
https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
As a workaround I'm skipping submitting the test results to Code Climate on a PR.  Instead they are only submitted to Code Climate on a push.  Hard to fully test this fix until some new Dependabot PRs some in and this PR is merged.

Don't submit the Code Climate test results on PRs

---

.github/workflows/dotnet-core.yml
.gitignore

This PR publishes any pushed tags onto the Corgibytes NuGet organization (https://www.nuget.org/profiles/corgibytes).
Depending on whether the package includes prerelease information, it will indicate being a pre-release, and won't be available as a standard package.

Published Beta/Prod packages to NuGet (#265)

---

.github/workflows/dotnet-core.yml

Fixes #340.  Now only beta and production releases are published to Nuget.org.  These are releases that have a tag.

Fix a bug in CI where alpha builds where getting published to Nuget.org.

---

CHANGELOG.md

Merge `release-0.4` branch into `main`.  This also merges the [v0.4.0](https://github.com/corgibytes/freshli-lib/releases/tag/v0.4.0) tag into `main`.  Not having this tag in main was causing the release notes workflow to fail as shown [here](https://github.com/corgibytes/freshli-lib/runs/3798306851?check_suite_focus=true).
```
Run gittools/actions/gitreleasemanager/create@v0.9.10
Command: dotnet-gitreleasemanager create --owner corgibytes --repository freshli-lib --token *** --targetDirectory /home/runner/work/freshli-lib/freshli-lib --milestone v0.4.0
/opt/hostedtoolcache/GitReleaseManager.Tool/0.11.0/x64/dotnet-gitreleasemanager create --owner corgibytes --repository freshli-lib --token *** --targetDirectory /home/runner/work/freshli-lib/freshli-lib --milestone v0.4.0
____ ____  __  __ …
```

Merge release-0.4 branch into main

---

.github/workflows/release-notes.yml

If a milestone has no closed issue the [release notes](https://github.com/corgibytes/freshli-lib/actions/workflows/release-notes.yml) CI will raise an error as [this](https://github.com/corgibytes/freshli-lib/runs/3808207026?check_suite_focus=true) one did:
```
Run gittools/actions/gitreleasemanager/create@v0.9.10
Command: dotnet-gitreleasemanager create --owner corgibytes --repository freshli-lib --token *** --targetDirectory /home/runner/work/freshli-lib/freshli-lib --milestone v0.5.0
/opt/hostedtoolcache/GitReleaseManager.Tool/0.11.0/x64/dotnet-gitreleasemanager create --owner corgibytes --repository freshli-lib --token *** --targetDirectory /home/runner/work/freshli-lib/freshli-lib --milestone v0.5.0
____ ____  __  __
/ ___|  _ \|  \/  |
| |  _| |_) | |\/| |
| |_| |  _ <| |  | | …
```

Fix release notes CI when no issues are closed for milestone

---

Corgibytes.Freshli.Lib.Test/Corgibytes.Freshli.Lib.Test.csproj
Corgibytes.Freshli.Lib.Test/Initializer.cs

Adds the Verify.DiffPlex package in attempt to improve the readability of Verify test output when there are differences between the received and verified files.
This was cherry-picked from a commit in #405.

Adds Verify.DiffPlex to improve output

---

.github/workflows/dotnet-core.yml

There are many different challenges present with publishing code coverage information to CodeClimate for all of the different platforms that are being built.
1. cc-test-reporter is not built for Windows
2. The GitHub Action that we're using
(paambaati/codeclimate-action@v3.0.0) does not support running the `format-coverage`, `sum-coverage` and `upload-coverage` commands as separate operations.
3. It is a non-trivial operation to correctly construct the environment variables that `cc-test-reporter` expects. See: https://github.com/paambaati/codeclimate-action/blob/c6ee9922e1b23fccfcc58a29c4c2072de52308a0/src/main.ts#L27-L44https://github.com/paambaati/codeclimate-action/blob/c6ee9922e1b23fccfcc58a29c4c2072de52308a0/src/main.ts#L27-L44
Hopefully, these issues will be overcome in the future, …

Limits code coverage reporting to Linux

---

.actrc
.config/dotnet-tools.json
.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.github/workflows/dependabot-automerge.yml
.github/workflows/dotnet-core.yml
.github/workflows/release-notes.yml
.gitignore
CHANGELOG.md

This also makes some improvements to the VS Code dev environment and makes it easier to test GitHub actions using `act`.

Fix build failures

---

Corgibytes.Freshli.Lib.Test/Corgibytes.Freshli.Lib.Test.csproj
Corgibytes.Freshli.Lib.Test/Initializer.cs
Corgibytes.Freshli.Lib.Test/Unit/Python/PythonVersionInfoTest.cs
Corgibytes.Freshli.Lib.Test/Unit/SemVerVersionInfoTest.cs
Corgibytes.Freshli.Lib.Test/Unit/Util/VersionHelperTest.cs
Corgibytes.Freshli.Lib/Corgibytes.Freshli.Lib.csproj
Corgibytes.Xunit.Extensions/Corgibytes.Xunit.Extensions.csproj

Requires more explicit types used in tests, possibly due to https://github.com/xunit/xunit/pull/2417. Note that we are intentionally not updating Elasticsearch to maintain compatibility with MetaCPAN.
My thinking is that we merge this, and then release a .NET 6 version of the NuGet package. I'm not sure on how the release process works; it looks like the prerelease action may be [failing due to incorrect versioning](https://github.com/corgibytes/freshli-lib/runs/8251441788?check_suite_focus=true) so any guidance on release would be appreciated.

Update all nuget dependencies
